package phonewave

import (
	"fmt"
	"os"
	"path/filepath"
	"time"

	"gopkg.in/yaml.v3"
)

// Config is the top-level phonewave.yaml structure.
type Config struct {
	LastSynced   time.Time     `yaml:"last_synced"`
	Repositories []RepoConfig  `yaml:"repositories"`
	Routes       []RouteConfig `yaml:"routes"`
}

// RepoConfig holds configuration for a single repository.
type RepoConfig struct {
	Path      string           `yaml:"path"`
	Endpoints []EndpointConfig `yaml:"endpoints"`
}

// EndpointConfig holds configuration for a single endpoint within a repo.
type EndpointConfig struct {
	Dir      string   `yaml:"dir"`
	Produces []string `yaml:"produces,flow"`
	Consumes []string `yaml:"consumes,flow"`
}

// RouteConfig holds a derived routing rule.
type RouteConfig struct {
	Kind     string   `yaml:"kind"`
	From     string   `yaml:"from"`
	To       []string `yaml:"to,flow"`
	Scope    string   `yaml:"scope"`
	RepoPath string   `yaml:"repo_path"`
}

// LoadConfig reads and parses a phonewave.yaml file.
// Relative paths in repositories[].path and routes[].repo_path are resolved
// to absolute paths based on the config file's directory.
func LoadConfig(path string) (*Config, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return nil, err
	}
	var cfg Config
	if err := yaml.Unmarshal(data, &cfg); err != nil {
		return nil, fmt.Errorf("parse %s: %w", path, err)
	}
	configDir := filepath.Dir(path)
	resolveRelPaths(&cfg, configDir)
	return &cfg, nil
}

// WriteConfig writes a Config to the given path as YAML.
// Absolute paths in repositories[].path and routes[].repo_path are converted
// to relative paths based on the config file's directory, so the config file
// is portable across machines when checked into git.
func WriteConfig(path string, cfg *Config) error {
	configDir := filepath.Dir(path)
	out := convertToRelPaths(cfg, configDir)

	data, err := yaml.Marshal(out)
	if err != nil {
		return err
	}

	header := "# phonewave.yaml\n# Auto-generated by phonewave\n\n"
	return os.WriteFile(path, []byte(header+string(data)), 0644)
}

// convertToRelPaths returns a shallow copy of cfg with absolute paths
// converted to relative paths. Paths that cannot be relativised (e.g.
// different Windows drive letters) are kept absolute.
func convertToRelPaths(cfg *Config, configDir string) *Config {
	out := *cfg

	repos := make([]RepoConfig, len(cfg.Repositories))
	for i, r := range cfg.Repositories {
		repos[i] = r
		repos[i].Path = toRel(configDir, r.Path)
	}
	out.Repositories = repos

	routes := make([]RouteConfig, len(cfg.Routes))
	for i, r := range cfg.Routes {
		routes[i] = r
		routes[i].RepoPath = toRel(configDir, r.RepoPath)
	}
	out.Routes = routes

	return &out
}

// resolveRelPaths converts relative paths in cfg to absolute, in place.
func resolveRelPaths(cfg *Config, configDir string) {
	for i := range cfg.Repositories {
		cfg.Repositories[i].Path = toAbs(configDir, cfg.Repositories[i].Path)
	}
	for i := range cfg.Routes {
		cfg.Routes[i].RepoPath = toAbs(configDir, cfg.Routes[i].RepoPath)
	}
}

func toRel(base, target string) string {
	if target == "" {
		return ""
	}
	rel, err := filepath.Rel(base, target)
	if err != nil {
		return target
	}
	return rel
}

func toAbs(base, target string) string {
	if target == "" || filepath.IsAbs(target) {
		return target
	}
	return filepath.Join(base, target)
}

// AddRepository appends a new repository with its endpoints to the config.
func (c *Config) AddRepository(path string, endpoints []Endpoint) {
	repo := RepoConfig{Path: path}
	for _, ep := range endpoints {
		repo.Endpoints = append(repo.Endpoints, EndpointConfig{
			Dir:      ep.Dir,
			Produces: ep.Produces,
			Consumes: ep.Consumes,
		})
	}
	c.Repositories = append(c.Repositories, repo)
}

// RemoveRepository removes a repository by path. Returns true if found.
func (c *Config) RemoveRepository(path string) bool {
	for i, repo := range c.Repositories {
		if repo.Path == path {
			c.Repositories = append(c.Repositories[:i], c.Repositories[i+1:]...)
			return true
		}
	}
	return false
}

// AllEndpoints returns all endpoints across all repositories as Endpoint values.
func (c *Config) AllEndpoints() []Endpoint {
	var all []Endpoint
	for _, repo := range c.Repositories {
		for _, ep := range repo.Endpoints {
			all = append(all, Endpoint{
				Dir:      ep.Dir,
				Produces: ep.Produces,
				Consumes: ep.Consumes,
			})
		}
	}
	return all
}

// UpdateRoutes re-derives routes from all endpoints and updates the config.
func (c *Config) UpdateRoutes() {
	// Derive routes per repository
	var allRoutes []RouteConfig
	for _, repo := range c.Repositories {
		var endpoints []Endpoint
		for _, ep := range repo.Endpoints {
			endpoints = append(endpoints, Endpoint{
				Dir:      ep.Dir,
				Produces: ep.Produces,
				Consumes: ep.Consumes,
			})
		}
		routes := DeriveRoutes(endpoints)
		for _, r := range routes {
			allRoutes = append(allRoutes, RouteConfig{
				Kind:     r.Kind,
				From:     r.From,
				To:       r.To,
				Scope:    r.Scope,
				RepoPath: repo.Path,
			})
		}
	}
	c.Routes = allRoutes
}
