package session

import (
	"fmt"
	"os"
	"path/filepath"

	phonewave "github.com/hironow/phonewave"
	"gopkg.in/yaml.v3"
)

// Compile-time check that FileConfigLoader implements phonewave.ConfigLoader.
var _ phonewave.ConfigLoader = (*FileConfigLoader)(nil)

// FileConfigLoader implements phonewave.ConfigLoader using the local filesystem.
type FileConfigLoader struct{}

// Load reads and parses a phonewave.yaml file.
func (FileConfigLoader) Load(path string) (*phonewave.Config, error) {
	return LoadConfig(path)
}

// Save writes a Config to the given path as YAML.
func (FileConfigLoader) Save(path string, cfg *phonewave.Config) error {
	return WriteConfig(path, cfg)
}

// LoadConfig reads and parses a phonewave.yaml file. Relative paths in the
// config are resolved to absolute paths using the config file's directory.
func LoadConfig(path string) (*phonewave.Config, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return nil, err
	}
	var cfg phonewave.Config
	if err := yaml.Unmarshal(data, &cfg); err != nil {
		return nil, fmt.Errorf("parse %s: %w", path, err)
	}

	configDir := filepath.Dir(path)
	resolveConfigPaths(&cfg, configDir)
	return &cfg, nil
}

// WriteConfig writes a Config to the given path as YAML. Absolute paths in
// the config are converted to relative paths based on the config file's directory.
func WriteConfig(path string, cfg *phonewave.Config) error {
	configDir := filepath.Dir(path)

	// Deep copy and relativize paths so the caller's cfg is not mutated.
	relative := relativizeConfigPaths(cfg, configDir)

	data, err := yaml.Marshal(relative)
	if err != nil {
		return err
	}

	header := "# phonewave.yaml\n# Auto-generated by phonewave\n\n"
	return os.WriteFile(path, []byte(header+string(data)), 0644)
}

// relativizeConfigPaths returns a shallow copy of cfg with absolute paths
// converted to relative paths based on configDir. Fields other than paths
// are shared (not deep-copied) since they are not mutated.
func relativizeConfigPaths(cfg *phonewave.Config, configDir string) *phonewave.Config {
	out := *cfg

	repos := make([]phonewave.RepoConfig, len(cfg.Repositories))
	for i, repo := range cfg.Repositories {
		repos[i] = repo
		if filepath.IsAbs(repo.Path) {
			if rel, err := filepath.Rel(configDir, repo.Path); err == nil {
				repos[i].Path = rel
			}
		}
	}
	out.Repositories = repos

	routes := make([]phonewave.RouteConfig, len(cfg.Routes))
	for i, route := range cfg.Routes {
		routes[i] = route
		if filepath.IsAbs(route.RepoPath) {
			if rel, err := filepath.Rel(configDir, route.RepoPath); err == nil {
				routes[i].RepoPath = rel
			}
		}
	}
	out.Routes = routes

	return &out
}

// resolveConfigPaths converts relative paths in cfg to absolute paths
// based on configDir. Paths that are already absolute are left unchanged.
func resolveConfigPaths(cfg *phonewave.Config, configDir string) {
	for i := range cfg.Repositories {
		p := cfg.Repositories[i].Path
		if !filepath.IsAbs(p) {
			cfg.Repositories[i].Path = filepath.Join(configDir, p)
		}
	}
	for i := range cfg.Routes {
		p := cfg.Routes[i].RepoPath
		if !filepath.IsAbs(p) {
			cfg.Routes[i].RepoPath = filepath.Join(configDir, p)
		}
	}
}
