package session

import (
	"fmt"
	"os"

	phonewave "github.com/hironow/phonewave"
	"gopkg.in/yaml.v3"
)

// LoadConfig reads and parses a phonewave.yaml file.
func LoadConfig(path string) (*phonewave.Config, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return nil, err
	}
	var cfg phonewave.Config
	if err := yaml.Unmarshal(data, &cfg); err != nil {
		return nil, fmt.Errorf("parse %s: %w", path, err)
	}
	return &cfg, nil
}

// WriteConfig writes a Config to the given path as YAML.
func WriteConfig(path string, cfg *phonewave.Config) error {
	data, err := yaml.Marshal(cfg)
	if err != nil {
		return err
	}

	header := "# phonewave.yaml\n# Auto-generated by phonewave\n\n"
	return os.WriteFile(path, []byte(header+string(data)), 0644)
}
