package session

import (
	"errors"
	"fmt"
	"io/fs"
	"os"
	"path/filepath"

	"github.com/hironow/phonewave/internal/domain"
	"gopkg.in/yaml.v3"
)

// manifest is the git-tracked portion of the config (config.yaml).
// It contains only repository endpoint declarations — no routes, no timestamps.
type manifest struct {
	Repositories []domain.RepoConfig `yaml:"repositories"`
}

// MigrateConfigIfNeeded detects a legacy phonewave.yaml at project root and
// moves it to .phonewave/config.yaml. It also ensures the state directory
// .gitignore includes !config.yaml. This is idempotent — calling it when
// migration is not needed is a no-op.
//
// projectRoot is the directory that contains (or should contain) .phonewave/.
func MigrateConfigIfNeeded(projectRoot string) error {
	legacyPath := filepath.Join(projectRoot, domain.LegacyConfigFile)
	newPath := domain.DefaultConfigPath(projectRoot)

	// Check if legacy file exists and new file does NOT
	if _, err := os.Stat(legacyPath); err != nil {
		if errors.Is(err, fs.ErrNotExist) {
			return nil // no legacy file — nothing to migrate
		}
		return fmt.Errorf("check legacy config %s: %w", legacyPath, err)
	}
	if _, err := os.Stat(newPath); err == nil {
		// Both exist — legacy is stale, remove it
		if rmErr := os.Remove(legacyPath); rmErr != nil {
			return fmt.Errorf("remove stale legacy config %s: %w", legacyPath, rmErr)
		}
		return nil
	}

	// Ensure state dir exists
	stateDir := filepath.Join(projectRoot, domain.StateDir)
	if err := os.MkdirAll(stateDir, 0755); err != nil {
		return fmt.Errorf("create state dir for migration: %w", err)
	}

	// Move legacy config into state dir
	data, err := os.ReadFile(legacyPath)
	if err != nil {
		return fmt.Errorf("read legacy config: %w", err)
	}
	if err := os.WriteFile(newPath, data, 0644); err != nil {
		return fmt.Errorf("write migrated config: %w", err)
	}
	if err := os.Remove(legacyPath); err != nil {
		return fmt.Errorf("remove legacy config: %w", err)
	}

	// Update .gitignore to include !config.yaml
	if err := EnsurePhonewaveStateDir(projectRoot); err != nil {
		return fmt.Errorf("update state dir gitignore: %w", err)
	}

	return nil
}

// LoadConfig reads config.yaml and merges it with the resolved state from
// .run/resolved.yaml (relative to the config directory). If resolved.yaml is
// missing, routes are derived from endpoints. If config.yaml still has inline
// routes (old format), they are used as-is for backward compatibility.
//
// Repository paths in the config are relative to the project root (parent of
// the state directory), NOT relative to the config file's directory.
func LoadConfig(path string) (*domain.Config, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return nil, err
	}
	var cfg domain.Config
	if err := yaml.Unmarshal(data, &cfg); err != nil {
		return nil, fmt.Errorf("parse %s: %w", path, err)
	}
	configDir := filepath.Dir(path)
	// Repo paths are relative to project root (parent of state dir)
	projectRoot := filepath.Dir(configDir)
	resolveRelPaths(&cfg, projectRoot)

	// If routes were loaded from old-format config with inline routes, keep them.
	if len(cfg.Routes) > 0 {
		return &cfg, nil
	}

	// Try loading resolved state from .run/resolved.yaml (configDir IS the state dir)
	resolvedPath := filepath.Join(configDir, ".run", domain.ResolvedStateFile)
	if rdata, rerr := os.ReadFile(resolvedPath); rerr == nil {
		var rs domain.ResolvedState
		if err := yaml.Unmarshal(rdata, &rs); err == nil {
			cfg.Routes = rs.Routes
			cfg.LastSynced = rs.LastSynced
			resolveRelPaths(&cfg, projectRoot)
		}
	}

	// Graceful fallback: derive routes from endpoints if still empty
	if len(cfg.Routes) == 0 && len(cfg.Repositories) > 0 {
		cfg.UpdateRoutes()
	}

	return &cfg, nil
}

// WriteConfig writes the config as two files:
//   - config.yaml: git-tracked manifest (repositories/endpoints only)
//   - .run/resolved.yaml: gitignored resolved state (routes, last_synced)
func WriteConfig(path string, cfg *domain.Config) error {
	configDir := filepath.Dir(path)
	// Repo paths are relative to project root (parent of state dir)
	projectRoot := filepath.Dir(configDir)
	rel := convertToRelPaths(cfg, projectRoot)

	// Write manifest (endpoints only, no routes or timestamp)
	m := manifest{Repositories: rel.Repositories}
	mdata, err := yaml.Marshal(m)
	if err != nil {
		return err
	}
	header := "# phonewave config\n# Auto-generated by phonewave\n\n"
	if err := os.WriteFile(path, []byte(header+string(mdata)), 0644); err != nil {
		return err
	}

	// Write resolved state (configDir IS the state dir)
	runDir := filepath.Join(configDir, ".run")
	if err := os.MkdirAll(runDir, 0755); err != nil {
		return fmt.Errorf("create .run dir: %w", err)
	}
	rs := domain.ResolvedState{
		LastSynced: rel.LastSynced,
		Routes:     rel.Routes,
	}
	rsdata, err := yaml.Marshal(rs)
	if err != nil {
		return err
	}
	resolvedPath := filepath.Join(runDir, domain.ResolvedStateFile)
	if err := os.WriteFile(resolvedPath, rsdata, 0644); err != nil {
		return fmt.Errorf("write resolved state: %w", err)
	}

	return nil
}

// WriteResolvedOnly writes only the .run/resolved.yaml file from the current
// cfg state (routes, last_synced) without touching config.yaml. This is used by
// doctor --repair to regenerate resolved state without rescanning the filesystem.
// stateDir is the .phonewave directory (parent of .run/).
func WriteResolvedOnly(stateDir string, cfg *domain.Config) error {
	projectRoot := filepath.Dir(stateDir)
	rel := convertToRelPaths(cfg, projectRoot)

	runDir := filepath.Join(stateDir, ".run")
	if err := os.MkdirAll(runDir, 0755); err != nil {
		return fmt.Errorf("create .run dir: %w", err)
	}
	rs := domain.ResolvedState{
		LastSynced: rel.LastSynced,
		Routes:     rel.Routes,
	}
	rsdata, err := yaml.Marshal(rs)
	if err != nil {
		return err
	}
	resolvedPath := filepath.Join(runDir, domain.ResolvedStateFile)
	if err := os.WriteFile(resolvedPath, rsdata, 0644); err != nil {
		return fmt.Errorf("write resolved state: %w", err)
	}
	return nil
}

// convertToRelPaths returns a shallow copy of cfg with absolute paths
// converted to relative paths. Paths that cannot be relativised (e.g.
// different Windows drive letters) are kept absolute.
func convertToRelPaths(cfg *domain.Config, configDir string) *domain.Config {
	out := *cfg

	repos := make([]domain.RepoConfig, len(cfg.Repositories))
	for i, r := range cfg.Repositories {
		repos[i] = r
		repos[i].Path = toRel(configDir, r.Path)
	}
	out.Repositories = repos

	routes := make([]domain.RouteConfig, len(cfg.Routes))
	for i, r := range cfg.Routes {
		routes[i] = r
		routes[i].RepoPath = toRel(configDir, r.RepoPath)
	}
	out.Routes = routes

	return &out
}

// resolveRelPaths converts relative paths in cfg to absolute, in place.
func resolveRelPaths(cfg *domain.Config, configDir string) {
	for i := range cfg.Repositories {
		cfg.Repositories[i].Path = toAbs(configDir, cfg.Repositories[i].Path)
	}
	for i := range cfg.Routes {
		cfg.Routes[i].RepoPath = toAbs(configDir, cfg.Routes[i].RepoPath)
	}
}

// resolvedStatePath returns the path to the resolved state file for a given
// config file path. Exported for migration tooling only.
func resolvedStatePath(cfgPath string) string {
	return filepath.Join(filepath.Dir(cfgPath), ".run", domain.ResolvedStateFile)
}

// ResolvedStateExists reports whether a resolved state file exists.
func ResolvedStateExists(cfgPath string) bool {
	_, err := os.Stat(resolvedStatePath(cfgPath))
	return err == nil || !errors.Is(err, fs.ErrNotExist)
}

func toRel(base, target string) string {
	if target == "" {
		return ""
	}
	rel, err := filepath.Rel(base, target)
	if err != nil {
		return target
	}
	return rel
}

func toAbs(base, target string) string {
	if target == "" || filepath.IsAbs(target) {
		return target
	}
	return filepath.Join(base, target)
}
